//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WinSigma.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_WINSIGMA_FORM               101
#define IDD_FORM_AZIENDE                102
#define IDR_MAINFRAME                   128
#define IDR_WINSIGTYPE                  129
#define IDC_HANDCUR                     130
#define IDB_IMAGELIST_AZIENDE           131
#define IDB_IMAGELIST_FATTURE           132
#define IDD_FORM_FATTURE                133
#define IDD_FORM_VERBALI                134
#define IDB_IMAGELIST_VERBALI           135
#define IDR_MENU_AZIENDE                136
#define IDR_TOOLBAR_AZIENDE             137
#define IDR_OPERATORI                   138
#define IDR_MENU_VERBALI                139
#define IDR_TOOLBAR_VERBALI             140
#define IDR_MENU_FATTURE                141
#define IDR_TOOLBAR_FATTURE             142
#define IDB_IMAGELIST_STRUMENTI         144
#define IDD_FORM_LISTINI                145
#define IDB_IMAGELIST_ARCHIVIO          146
#define IDB_IMAGELIST_LISTINI           148
#define IDD_FORM_STRUMENTI              149
#define IDD_FORM_OPERATORI              150
#define IDR_MENU_LISTINI                151
#define IDR_TOOLBAR_LISTINI             152
#define IDR_MENU_PAGAMENTI              153
#define IDR_TOOLBAR_OPERATORI           154
#define IDD_DIALOG_CONNESSIONE          155
#define IDR_MENU_MATERIALI              156
#define IDR_TOOLBAR_PAGAMENTI           157
#define IDD_DIALOG_AZIENDA              158
#define IDR_TOOLBAR_MATERIALI           159
#define IDD_FORM_PAGAMENTI              160
#define IDR_MENU_OPERATORI              161
#define IDD_FORM_MATERIALI              162
#define IDR_MENU_MARCHI                 163
#define IDR_TOOLBAR1                    164
#define IDB_IMAGELIST_SERIE             165
#define IDD_DIALOG_CATEGORIE            166
#define IDR_TOOLBAR_MARCHI              167
#define IDD_DIALOG_SERVIZILISTINO       168
#define IDD_DIALOG_SERVIZIFATTURA       169
#define IDD_DIALOG_ATTIVALISTINO        170
#define IDD_DIALOG_TROVA_AZIENDA        171
#define IDD_DIALOG_SERIE                172
#define IDD_DIALOG_EMISSIONE_CERTIFICATI 173
#define IDD_DIALOG_STAMPA_CERTIFICATI   174
#define IDD_DIALOG_SAVEPRN_VERBALI      175
#define IDI_ICON_MSGBOX                 176
#define IDD_FORM_MARCHI                 177
#define IDB_BITMAP1                     178
#define IDB_IMAGELIST_STAMPA_CERT       183
#define IDD_FORM_ARCHIVIO_VERBALI       184
#define IDD_DIALOG_FIND_VERBALI         185
#define IDD_FORM_ARCHIVIO_CERTIFICATI   188
#define IDD_FORM_ARCHIVIO_FATTURE       192
#define IDD_DIALOG_SERVIZI_FATTURA      193
#define IDD_DIALOG_SERVIZI_PIPPO        194
#define IDD_DIALOG_STAMPA_FATTURE       195
#define IDR_MENU_ARCHIVIO_VERBALI       209
#define IDR_MENU_ARCHIVIO_CERTIFICATI   210
#define IDR_MENU_ARCHIVIO_FATTURE       211
#define IDR_TOOLBAR_ARCHIVIO_VERBALI    212
#define IDR_TOOLBAR_ARCHIVIO_CERTIFICATI 214
#define IDR_TOOLBAR_ARCHIVIO_FATTURE    215
#define IDD_DIALOG_INSERT_VERBALI       216
#define IDD_DIALOG_PRINT_VERBALI        217
#define IDD_DIALOG_ARCHIVIO_AZIENDE     218
#define IDD_DIALOG_PREVIEW              219
#define IDD_DIALOG_MODIFICA_CERTIFICATO 220
#define IDD_DIALOG_EFFETTI              221
#define IDR_TOOLBAR_ARCHIVIO_CERT       222
#define IDD_DIALOG_STAMPAMINUTE         226
#define IDD_DIALOG_ETICHETTE            227
#define IDD_DIALOG_REPORT_VERBALI       228
#define IDD_DIALOG_INSERT_VERBALE       229
#define IDD_DIALOG_FATTURA_PROFORMA     230
#define IDD_DIALOG_ARCHIVIA_FATTURE     234
#define IDB_LOGO_QUADRANTE              239
#define IDD_DIALOG_EMENDAMENTI          240
#define IDD_DIALOG_ESPORTA_FATTURE      245
#define IDD_FORM_STATISTICHE_PROVE      246
#define IDD_FORM_STATISTICHE_FATTURATO  248
#define IDD_FORM_TOTALI_FATTURATO       251
#define IDD_FORM_ESPORTAZIONE_CSV       253
#define IDI_ICON_CLOCK                  255
#define IDI_ICON_QX                     256
#define IDI_ICON_DISK                   257
#define IDR_MENU_VERBALI_WS2            258
#define IDD_DIALOG_DB_REMOTO            259
#define IDB_BITMAP_ELETT                263
#define IDD_DIALOG_ESPORTA_XML          269
#define IDC_EDIT_NOME                   1000
#define IDC_EDIT_INDIRIZZO              1001
#define IDC_EDIT_CAP                    1002
#define IDC_EDIT_CITTA                  1003
#define IDC_EDIT_TELEFONO               1004
#define IDC_EDIT_E_MAIL                 1005
#define IDC_EDIT_CELL                   1006
#define IDC_EDIT_FAX                    1007
#define IDC_EDIT_CODICE_FISCALE         1008
#define IDC_EDIT_P_IVA                  1009
#define IDC_EDIT_CODICE_CLIENTE         1010
#define IDC_EDIT_BANCA                  1011
#define IDC_EDIT_ABI                    1012
#define IDC_EDIT_CAB                    1013
#define IDC_EDIT_DSN_NAME               1014
#define IDC_EDIT_CUP                    1014
#define IDC_EDIT_UTENTE                 1015
#define IDC_EDIT_CIG                    1015
#define IDC_EDIT_PASSWORD               1016
#define IDC_EDIT_ORDINE                 1016
#define IDC_EDIT_NOTE                   1017
#define IDC_EDIT_CONTRATTO              1017
#define IDC_EDIT_PROVINCIA              1018
#define IDC_EDIT_NUMERODDT              1018
#define IDC_EDIT_RAGIONE_SOCIALE        1019
#define IDC_EDIT_COGNOME                1020
#define IDC_CHECK_AZIENDA_IMPORTANTE    1021
#define IDC_CHECK_SOPSESO               1022
#define IDC_CHECK_RIBA                  1023
#define IDC_CHECK_PROVAA                1024
#define IDC_CHECK_IMPORTANTE            1025
#define IDC_CHECK_PROVAA2               1025
#define IDC_CHECK_OGNISERIE             1026
#define IDC_CHECK_NUOVOCERT             1027
#define IDC_CHECK_PRN_VERBALE           1028
#define IDC_CHECK_PREDEFINITO           1029
#define IDC_CHECK_CERTIFICATIOGNISERIE  1030
#define IDC_CHECK_PERSERVIZIO           1031
#define IDC_CHECK_ZOOM                  1032
#define IDC_CHECK_CALCOLO_PAGINE        1033
#define IDC_CHECK_DUPLICATO             1034
#define IDC_CHECK_REPORT                1035
#define IDC_DATETIMEPICKER_INIZIO       1043
#define IDC_DATETIMEPICKER_FINE         1044
#define IDC_EDIT_VERIFICA               1046
#define IDC_COMBO_LIVELLO               1047
#define IDC_EDIT_CODICE                 1049
#define IDC_EDIT_DESCRIZIONE            1055
#define IDC_EDIT_GIORNI                 1056
#define IDC_EDIT_PRODUTTORE             1056
#define IDC_COMBO_ALLINEAMENTO          1057
#define IDC_EDIT_STABILIMENTO           1057
#define IDC_EDIT_AUTORE                 1062
#define IDC_EDIT_NCATEGORIE             1063
#define IDC_EDIT_INIZIO                 1064
#define IDC_EDIT_FINE                   1065
#define IDC_EDIT_NSERVIZI               1066
#define IDC_LIST_CATEGORIE              1067
#define IDC_LIST_SERVIZI                1068
#define IDC_BUTTON_CERCA                1071
#define IDC_EDIT_NOMEAZIENDA            1072
#define IDC_EDIT_CODICEAZIENDA          1073
#define IDC_EDIT_CODICELISTINO          1074
#define IDC_EDIT_NOMELISTINO            1075
#define IDC_EDIT_CATEGORIA              1079
#define IDC_EDIT_NPROVINI               1081
#define IDC_RADIO_PERPROVINO            1084
#define IDC_RADIO_PERSERIE              1085
#define IDC_COMBO_CERTIFICATO           1086
#define IDC_CHECK_PROVAB                1087
#define IDC_COMBO_CERTIFICATO2          1088
#define IDC_COMBO_CODICE                1089
#define IDC_CHECK_PROVAB2               1089
#define IDC_CHECK_EMISSIONE             1090
#define IDC_MASKEDBOX_PREZZO            1091
#define IDC_EDIT_CODICEVECCHIO          1092
#define IDC_MASKEDBOX_IMPORTO           1092
#define IDC_MASKEDBOX_PREZZO2           1092
#define IDC_EDIT_NOMEVECCHIO            1093
#define IDC_EDIT_DALVECCHIO             1094
#define IDC_EDIT_CODICENUOVO            1095
#define IDC_EDIT_NOMENUOVO              1096
#define IDC_DATETIMEPICKER_DALNUOVO     1097
#define IDC_EDIT_RAG_SOC                1098
#define IDC_EDIT_CODE                   1099
#define IDC_EDIT_EMAIL                  1100
#define IDC_EDIT_CODFISC                1101
#define IDC_EDIT_PIVA                   1102
#define IDC_COMBO_TIPOPAGAMENTO         1103
#define IDC_EDIT_SCONTO                 1104
#define IDC_EDIT_CODDEST                1105
#define IDC_EDIT_PEC                    1106
#define IDC_LIST_VERBALI                1108
#define IDC_EDIT_APERTI                 1109
#define IDC_EDIT_DAFATTURARE            1110
#define IDC_EDIT_TOTALEVERBALI          1111
#define IDC_BUTTON_OK                   1113
#define IDC_EDIT_NOME_CODICE            1115
#define IDC_LIST_RISULTATI              1117
#define IDC_BUTTON_CANCEL               1119
#define IDC_CODICE                      1120
#define IDC_STATIC_FIND                 1121
#define IDC_NOME                        1122
#define IDC_EDIT_TIPOVERBALE            1123
#define IDC_EDIT_NUMVERBALE             1124
#define IDC_EDIT_COD_AZ_CERTIFICATO     1127
#define IDC_EDIT_COD_AZ_FATTURA         1128
#define IDC_EDIT_COD_AZ_IMPRESA         1129
#define IDC_EDIT_NOME_AZ_CERTIFICATO    1130
#define IDC_EDIT_NOME_AZ_FATTURA        1131
#define IDC_EDIT_NOME_AZ_IMPRESA        1132
#define IDC_BUTTON_FIND                 1133
#define IDC_EDIT_LETTERA                1134
#define IDC_EDIT_CANTIERE               1135
#define IDC_EDIT_DIRETTORE              1136
#define IDC_EDIT_PROPRIETARIO           1137
#define IDC_EDIT_PROVE                  1138
#define IDC_EDITMATERIALE               1139
#define IDC_CHECK_URGENZA               1140
#define IDC_CHECK_RITIRO                1141
#define IDC_LIST_SERIE                  1142
#define IDC_EDIT_NUMSERIE               1143
#define IDC_EDIT_RICHIEDENTE            1144
#define IDC_DATE_ACCETTAZIONE           1145
#define IDC_DATE_CONSEGNA               1146
#define IDC_BUTTON_AGGIUNGI             1147
#define IDC_BUTTON_ELIMINA              1148
#define IDC_BUTTON_MODIFICA             1149
#define IDC_EDIT_POSIZIONE              1151
#define IDC_COMBO_TIPI_CERTIFICATO      1152
#define IDC_EDIT_RICHIESTI              1154
#define IDC_EDIT_CONSEGNATI             1155
#define IDC_EDIT_NUMSERVIZI             1156
#define IDC_DATETIMEPICKER_PRELIEVO     1159
#define IDC_EDIT_SIGLA                  1161
#define IDC_EDIT_MATERIALE              1162
#define IDC_EDIT_SIGLA2                 1162
#define IDC_EDIT_STRUTTURA              1163
#define IDC_STATIC_DIM1                 1164
#define IDC_STATIC_DIM2                 1165
#define IDC_STATIC_DIM3                 1166
#define IDC_EDIT_DIM1                   1167
#define IDC_EDIT_DIM3                   1168
#define IDC_CHECK_LISTINOGENERALE       1168
#define IDC_EDIT_DIM2                   1169
#define IDC_STATIC_DATA_PRELIEVO        1170
#define IDC_STATIC_MATERIALE            1171
#define IDC_STATIC_STRUTTURA            1172
#define IDC_STATIC_SIGLA                1173
#define IDC_COMBO_OPERATORE             1174
#define IDC_STATIC_SIGLA2               1174
#define IDC_STATIC_DNS                  1175
#define IDC_LIST_CERTIFICATI            1176
#define IDC_EDIT_COSTO                  1177
#define IDC_EDIT_CODICE_PRIMO           1178
#define IDC_CHECK_LETTERA               1180
#define IDC_LIST_CERTIFICATI_STAMPABILI 1181
#define IDC_CHECK_SPEDIZIO              1182
#define IDC_CHECK_SPEDIZI               1183
#define IDC_CHECK_SPEDIZIONE            1184
#define IDC_EDIT_DATI                   1185
#define IDC_CHECK_SPED_INT              1186
#define IDC_CHECK_PRIVATO               1188
#define IDC_CHECK_LISTINO               1189
#define IDC_EDIT_LOCALITA               1194
#define IDC_BUTTON_AUTO_PROVE           1198
#define IDC_BUTTON_AUTO_MAT             1199
#define IDC_CHECK_SPED_ALTRO            1205
#define IDC_BUTTON_NO                   1206
#define IDC_STATIC_SALVA                1207
#define IDC_CHECK_PRN_VCARTALIBERA      1208
#define IDC_CHECK_PRN_MINUTA            1209
#define IDC_CHECK_LUNGA_SCADENZA        1210
#define IDC_EDIT_NUM_MOD                1211
#define IDC_BUTTON_MOD_NUM              1212
#define IDC_BUTTON_DATI_PROVINI         1213
#define IDC_COMBO_TIPO_PAGAMENTO        1215
#define IDC_EDIT_SCADENZA               1216
#define IDC_EDIT_NUM_FATTURA            1219
#define IDC_DATETIMEPICKER_DATA_FATTURA 1220
#define IDC_EDIT_TIPO_DOCUMENTO         1221
#define IDC_DATETIMEPICKER_DATA_ORDINE  1221
#define IDC_EDIT_DATI_CLIENTE           1222
#define IDC_DATETIMEPICKER_DATA_CONTRATTO 1222
#define IDC_DATETIMEPICKER_DATA_DDT     1223
#define IDC_EDIT_COD_CLIENTE            1224
#define IDC_BUTTON_ADD_SERVIZIO         1238
#define IDC_BUTTON_DEL_SERVIZIO         1239
#define IDC_BUTTON_MODIFY_SERVIZIO      1240
#define IDC_EDIT_IMPORTO                1241
#define IDC_EDIT_IVA                    1242
#define IDC_EDIT_TOT_FATTURA            1243
#define IDC_BUTTON_SELEZIONE            1244
#define IDC_BUTTON_CONFERMA             1245
#define IDC_EDIT_PROPOSTO               1246
#define IDC_CHECK_AGGIUNTIVO            1247
#define IDC_COMBO_PRODUTTORE            1248
#define IDC_COMBO_STABILIMENTO          1249
#define IDC_EDIT_NOMEFILE               1250
#define IDC_BUTTON_ARCHIVIO_AZIENDE     1251
#define IDC_BUTTON_NEXT                 1252
#define IDC_BUTTON_QUADRI               1253
#define IDC_BUTTON_TUTTE                1254
#define IDC_BUTTON_COPY                 1255
#define IDC_BUTTON_VERBALI              1256
#define IDC_BUTTON_RICERCA              1257
#define IDC_BUTTON_STAMPA               1258
#define IDC_BUTTON_PRINT_FATTURA        1259
#define IDC_BUTTON_SFOGLIA              1260
#define IDC_BUTTON_FATTURA_XML          1260
#define IDC_STATIC_MARCHIO              1261
#define IDC_CHECK_DOMANDA_SOTTOSCRITTA  1262
#define IDC_COMBO_TIPOCERTIFICATO       1263
#define IDC_EDIT_ORA_CONSEGNA           1264
#define IDC_CHECK_SPED_FATTURA          1265
#define IDC_CHECK_SPED_IMPRESA          1266
#define IDC_COMBO_MATERIALE             1267
#define IDC_BUTTON_CERTIFICATI          1268
#define IDC_ELIMINA_DOC                 1268
#define IDC_BUTTON_NON_STAMPATI         1269
#define IDC_EDIT_MACCHINA               1270
#define IDC_CHECK_SPERIMENTATORE        1271
#define IDC_RADIO_CANTIERE              1272
#define IDC_RADIO_DIR_LAVORI            1273
#define IDC_RADIO_CERTIFICATO           1274
#define IDC_RADIO_FATTURA               1275
#define IDC_RADIO_IMPRESA               1276
#define IDC_EDIT_CHIAVE                 1277
#define IDC_STATIC_NUMERO               1278
#define IDC_RADIO_STRUTTURA             1278
#define IDC_STATIC_DANUMERO             1278
#define IDC_EDIT_NUMERO                 1279
#define IDC_STATIC_ANNO                 1280
#define IDC_COMBO_ANNO                  1281
#define IDC_STATIC_INTESTAZIONE         1282
#define IDC_STATIC_RAGIONE_SOCIALE      1283
#define IDC_STATIC_CODICE               1284
#define IDC_RADIO_INTESTAZIONE_CERTIFICATI 1285
#define IDC_RADIO_INTESTAZIONE_FATTURE  1286
#define IDC_RADIO_IMPRESA_COSTRUTTRICE  1287
#define IDC_RADIO_DESTINATARIO_CERTIFICATI 1288
#define IDC_LIST_RISULTATO_RICERCA      1289
#define IDC_STATIC_SELEZIONE            1290
#define IDC_STATIC_NUMERO_CERTIFICATO   1291
#define IDC_EDIT_NUMERO_CERTIFICATO     1292
#define IDC_EDIT_NUMEROVERBALE          1293
#define IDC_STATIC_NUMERO_VERBALE       1294
#define IDC_STATIC_PARTITA_IVA          1295
#define IDC_EDIT_PARTITA_IVA            1296
#define IDC_COMBO_DOCUMENTO             1297
#define IDC_COMBO_VERBALE               1298
#define IDC_COMBO_CATEGORIA             1299
#define IDC_COMBO_SERVIZIO              1300
#define IDC_EDIT_QUANTITA               1301
#define IDC_EDIT_PREZZO                 1302
#define IDC_LIST_FATTURE                1303
#define IDC_STATIC_SELECT               1304
#define IDC_EDIT_NUMERO_VERBALE         1305
#define IDC_COMBO_CONSEGNA              1306
#define IDC_EDIT_SNERVAMENTO            1307
#define IDC_EDIT_DESTINATARIO           1308
#define IDC_EDIT_SPESE_SPEDIZIONE       1309
#define IDC_EDIT_RIFERIMENTI            1310
#define IDC_EDIT_TIPO_PAGAMENTO         1311
#define IDC_MASKEDBOX_SPESE_SPED        1312
#define IDC_EDIT_TIPOPAGAMENTO          1313
#define IDC_EDIT_DATA                   1314
#define IDC_MASKEDBOX_SPESE_SPEDIZIONE  1315
#define IDC_CHECK_NO_CALCOLO            1317
#define IDC_CHECK_RESPONSABILE          1318
#define IDC_CHECK_PERPROVINO            1319
#define IDC_CHECK_ETICHETTE             1320
#define IDC_EDIT_SPESE_SPED             1321
#define IDC_EDIT_COD_FISCALE            1322
#define IDC_CHECK_NON_DICHIARATA        1323
#define IDC_EDIT_NORMA                  1324
#define IDC_CHECK_VERBALE_PRELIEVO_NON_DICHIARATO 1324
#define IDC_COMBO_ID                    1325
#define IDC_STATIC_SPEDIZIONE           1327
#define IDC_STATIC_INDIRIZZO_SPEDIZIONE 1328
#define IDC_EDIT_INDIRIZZO_SPEDIZIONE   1329
#define IDC_STATIC_CAP_SPEDIZIONE       1330
#define IDC_EDIT_CAP_SPEDIZIONE         1331
#define IDC_STATIC_CITTA_SPEDIZIONE     1332
#define IDC_EDIT_CITTA_SPEDIZIONE       1333
#define IDC_STATIC_PROVINCIA_SPEDIZIONE 1334
#define IDC_EDIT_PROVINCIA_SPEDIZIONE   1335
#define IDC_BUTTON_ZOOM                 1336
#define IDC_STATIC_PREVIEW              1337
#define IDC_EDIT_BANCA_APPOGGIO         1338
#define IDC_LIST_AZIENDE_VECCHIE        1339
#define IDC_STATIC_CAMPI_RICERCA        1340
#define IDC_STATIC_INDIRIZZO            1341
#define IDC_STATIC_BANCA_APPOGGIO       1342
#define IDC_BUTTON_GENERA_CODICE        1345
#define IDC_EDIT_PARZIALE               1346
#define IDC_EDIT_TOTALE                 1347
#define IDC_EDIT_PROV                   1348
#define IDC_COMBO_PAGAMENTO             1349
#define IDC_COMBO_EMISSIONE             1350
#define IDC_BUTTON_INSERT               1356
#define IDC_DATETIMEPICKER_ACCETTAZIONE 1358
#define IDC_EDIT_IMPONIBILE             1359
#define IDC_EDIT_ALIQUOTA               1360
#define IDC_COMBO_AGGIUNTIVO            1361
#define IDC_SCROLLBAR                   1362
#define IDC_STAMPA                      1363
#define IDC_EDIT_NAZIENDE               1364
#define IDC_STATIC_SCADENZE             1365
#define IDC_STATIC_PRIMA_SCADENZA       1366
#define IDC_EDIT_PRIMA_SCADENZA         1367
#define IDC_STATIC_NUMERO_RATE          1368
#define IDC_EDIT_NUMERO_RATE            1369
#define IDC_EDIT_DATA_ND                1370
#define IDC_EDIT_PAGINE                 1373
#define IDC_DATE_EMISSIONE              1374
#define IDC_EDIT_VERBALE                1375
#define IDC_STATIC_VERBALI_FARLOCCHI    1376
#define IDC_BUTTON_MODIFICA_VFARLOCCO   1377
#define IDC_BUTTON_ELIMINA_VFARLOCCO    1378
#define IDC_STATIC_PIVA_CF              1381
#define IDC_EDIT_TITOLI                 1382
#define IDC_EDIT_NUM_COPIE              1383
#define IDC_DATA_DUPLICATO              1384
#define IDC_CHECK_PERSERIE              1385
#define IDC_CHECK_CONCESSIONE           1386
#define IDC_EDIT_A_FATTURA              1387
#define IDC_EDIT_DA_FATTURA             1388
#define IDC_LIST_EFFETTI                1389
#define IDC_EDIT_DA_ELETT               1389
#define IDC_EDIT_PROGRESSIVO            1389
#define IDC_EDIT_SCONTO_FATTURA         1390
#define IDC_EDIT_A_ELETT                1390
#define IDC_EDIT_ANNO                   1390
#define IDC_EDIT_IMPORTO_SCONTATO       1391
#define IDC_EDIT_IMPORTOSCONTATO        1392
#define IDC_CHECK_COMMENTOMATERIALE     1394
#define IDC_LIST_MINUTE                 1395
#define IDC_EDIT_DAL                    1396
#define IDC_EDIT_AL                     1397
#define IDC_COMBO_PARTENZA              1399
#define IDC_CHECK_EMENDAMENTO           1400
#define IDC_EDIT_TIPO_DOC               1401
#define IDC_STATIC_DATI                 1402
#define IDC_LIST1                       1403
#define IDC_LIST_VERBALIDAFATTURARE     1403
#define IDC_LIST_RISULTATO              1403
#define IDC_LIST_DB_REMOTO              1403
#define ID_BUTTON_RICERCA               1404
#define IDC_DATE_AL                     1409
#define IDC_DATE_DAL                    1410
#define IDC_BUTTON_RICERCA_AVANZATA     1415
#define IDC_DATETIMEPICKER_DATA_EMISSIONE 1421
#define IDC_EDIT_SPESE                  1425
#define IDC_EDIT_CIN                    1427
#define IDC_EDIT_CC                     1428
#define IDC_EDIT_NUMCOPIE               1429
#define IDC_EDIT_PAGAMENTO              1430
#define IDC_COMBO_TIPO                  1431
#define IDC_EDIT_PROVINI_PER_SERIE      1442
#define IDC_DATETIMEPICKER_SCADENZA     1443
#define IDC_STATIC_DA_FATTURA           1444
#define IDC_STATIC_A_FATTURA            1445
#define IDC_STATIC_CARTACEA             1446
#define IDC_STATIC_ELETTRONICA          1447
#define IDC_STATIC_PROGRESSIVO          1447
#define IDC_CHK_VERBALI_APERTI          1448
#define IDC_STATIC_DA_FATTURA2          1448
#define IDC_STATIC_A_FATTURA2           1449
#define IDC_RADIO_SIGLA                 1455
#define IDC_RADIO_INT_CERT              1457
#define IDC_RADIO_INT_FATTURA           1458
#define IDC_RADIO_STRUTT                1460
#define IDC_CHECK_GEOLOGIA              1462
#define IDC_EDIT_COMMENTO               1463
#define IDC_PROGRESS_LOAD               1465
#define IDC_STATIC_LOADPROGESS          1468
#define IDC_STATIC_ICON                 1469
#define IDC_EDIT_NUM_CERTIFICATI        1471
#define IDC_CHECK_INVALIDPICKER         1473
#define IDC_CHECK_BONIFICO              1474
#define IDC_EDIT_FATTURA                1475
#define IDC_STATIC_PRIMO                1476
#define IDC_STATIC_SECONDO              1477
#define IDC_CERTIFICATO                 1478
#define IDC_BUTTON_EMENDA               1479
#define IDC_STATIC_CERTIFICATO          1480
#define IDC_STATIC_EMENDAMENTI          1481
#define IDC_TREE_EMENDAMENTI            1482
#define IDC_BUTTON_CREA                 1483
#define IDC_BUTTON_CTOE                 1485
#define IDC_COMBO_TIPOCERTIFICATO2      1487
#define IDC_COMBO_CAP                   1489
#define IDC_STATIC_ANUMERO              1490
#define IDC_EDIT_ANUMERO                1491
#define IDC_EDIT_DANUMERO               1492
#define IDC_EDIT_CODFISCALE             1496
#define IDC_STATIC_RIT_ACCONTO          1499
#define IDC_EDIT_RIT_ACCONTO            1500
#define IDC_EDIT_TOT_RIT_ACCONTO        1501
#define IDC_RADIO_NUMERO                1504
#define IDC_STATIC_VERSION              1505
#define IDC_COMBO_ANNI                  1508
#define IDC_STATIC_ESPORTA_FATTURE      1509
#define IDC_STATIC_STATISTICHE_PROVE    1510
#define IDC_STATIC_TIPO                 1513
#define IDC_STATIC_RISULTATO            1516
#define IDC_BUTTON_REPORT               1517
#define IDC_COMBO_CLIENTE               1518
#define IDC_COMBO_MESE                  1520
#define IDC_STATIC_CLIENTE              1521
#define IDC_STATIC_MESE                 1522
#define IDC_STATIC_FATTURATO            1525
#define IDC_LIST_FATTURATO              1526
#define IDC_BUTTON_STAMPA_REPORT        1527
#define IDC_BUTTON_ORDINA_VERBALI       1528
#define IDC_BUTTON_ORDINA_IMPONIBILE    1529
#define IDC_EDIT_CODICE_GEST            1530
#define IDC_STATIC_CODICE_GEST          1531
#define IDC_STATIC_RICERCA_CLIENTE      1532
#define IDC_BUTTON_TROVA_CLIENTE        1534
#define IDC_STATIC_RICERCA              1535
#define IDC_STATIC_PATH                 1536
#define IDC_EDIT_PATH                   1537
#define IDC_STATIC_TIPO_PROVA           1538
#define IDC_COMBO_TIPO_PROVA            1539
#define IDC_STATIC_TOTALI_FATTURATO     1540
#define IDC_BUTTON_CALCOLA              1541
#define IDC_LIST_TOTALI_FATTURATO       1542
#define IDC_COMBO_CERTIFICATO3          1545
#define IDC_CHECK_PROVAA3               1546
#define IDC_CHECK_PROVAB3               1547
#define IDC_STATIC_TERZO                1548
#define IDC_COMBO_TIPOCERTIFICATO3      1549
#define IDC_CHECK_ADERENZA              1554
#define IDC_EDIT_SIGLA_FORNITORE        1555
#define IDC_STATIC_SIGLA_FORNITORE      1556
#define IDC_STATIC_VERBALE_PRELIEVO     1560
#define IDC_EDIT_VERBALE_PRELIEVO       1561
#define IDC_STATIC_QUARTO               1562
#define IDC_COMBO_CERTIFICATO4          1563
#define IDC_CHECK_PROVAA4               1564
#define IDC_CHECK_PROVAB4               1565
#define IDC_COMBO_TIPOCERTIFICATO4      1566
#define IDC_STATIC_QUINTO               1566
#define IDC_EDIT_OSSERVAZIONI           1567
#define IDC_COMBO_CERTIFICATO5          1567
#define IDC_DATETIMEPICKER_DA           1568
#define IDC_CHECK_PROVAA5               1568
#define IDC_DATETIMEPICKER_A            1569
#define IDC_CHECK_PROVAB5               1569
#define IDC_STATIC_DA                   1570
#define IDC_STATIC_A                    1571
#define IDC_BUTTON_DB_REMOTO            1573
#define IDC_BUTTON_ID_MISSING           1574
#define IDC_BUTTON_ID_PRESENT           1575
#define IDC_BUTTON_AGGIORNA             1575
#define IDC_BUTTON_TUTTI                1576
#define IDC_CHECK_PA                    1577
#define IDC_CHECK_IVADIFF               1578
#define IDC_STATIC_ELETT                1585
#define IDC_CHECK_HEADER                1586
#define IDC_STATIC_ALARM_NOTE           1587
#define IDC_STATIC_ESPORTA_XML          1588
#define IDC_STATIC_FATTURE              1589
#define ID_AZIENDA_MODIFICA             32771
#define ID_VERBALE_MODIFICA             32772
#define ID_FATTURA_EMETTI               32773
#define ID_AZIENDA_NUOVA                32774
#define ID_CATEGORIA_NUOVA              32775
#define ID_NUOVO                        32776
#define ID_MODIFICA                     32777
#define ID_ELIMINA                      32784
#define ID_CATEGORIA_ELIMINA            32804
#define ID_CATEGORIA_MODIFICA           32805
#define ID_SERVIZI_NUOVO                32806
#define ID_SERVIZI                      32807
#define ID_SERVIZI_MODIFICA             32807
#define ID_SERVIZI_ELIMINA              32808
#define ID_LISTINI_COPIA                32812
#define ID_LISTINI_ATTIVA               32813
#define ID_LISTINI_DISATTIVA            32827
#define ID_TROVA                        32831
#define ID_VERBALE_ELIMINA              32833
#define ID_VERBALE_NUOVO                32834
#define ID_VERBALI_NUOVO                32836
#define ID_NUOVO_VERBALE                32839
#define ID_LISTINI_STAMPA               32841
#define ID_ANNULLA                      32842
#define ID_BUTTON_EMISSIONE_CERTIFICATI 32844
#define ID_PRINT_VERBALE                32845
#define ID_PRINT_MINUTA                 32846
#define ID_BUTTON_AVVIA_EMISSIONE       32847
#define ID_PRN_CARTA_INTESTATA          32849
#define ID_PRN_CARTA_LIBERA             32850
#define ID_DATI_PROVINI                 32854
#define ID_CHIUDI_VERBALE               32868
#define ID_METTI_IN_FATTURAZIONE        32869
#define ID_STAMPA                       32878
#define ID_FIND_VERB_CANTIERE           32879
#define ID_FIND_VERB_DIR_LAVORI         32880
#define ID_FIND_VERB_CERTIFICATO        32881
#define ID_FIND_VERB_FATTURA            32882
#define ID_FIND_VERB_IMPRESA            32883
#define ID_FATTURA_STAMPA_SINGOLA       32887
#define ID_FATTURA_STAMPA_MULTIPLA      32888
#define ID_SERVIZI_NUOVONOTA            32889
#define ID_PRINTPROFORMA                32890
#define ID_SALVA_FATTURA                32891
#define ID_VISUALIZZA_FATTURA           32892
#define ID_BUTTON_MOD_CERTIFICATO       32894
#define ID_CERTIFICATI_MODIFICA         32895
#define ID_BUTTON_MODIFICA_CERTIFICATO  32896
#define ID_ARCHIVIA_FATTURA             32897
#define ID_BUTTO_REFRESH_VERBALI        32898
#define ID_NUOVA_SVERBALE               32899
#define ID_NUOVA_SENZAVERBALE           32900
#define ID_RIPRISTINA_FATTURA           32901
#define IDC_ANTEPRIMA_FATTURA           32902
#define ID_APRI_VERBALE                 32903
#define ID_APRI_CERTIFICATO             32904
#define ID_STAMPAEFFETTI                32907
#define ID_EMETTI_NOTA_CREDITO          32908
#define ID_CREA_NOTA_CREDITO            32909
#define ID_ARCHIVIA_NOTACREDITO         32910
#define ID_BTN_EILIMINACERTIFICATO      32912
#define ID_BUTTON_AGGIORNAALBERO        32914
#define ID_AGGIORNA_ALBERO              32916
#define ID_BUTTON_AGGIORNA_FATTURE      32921
#define ID_SBLOCCO_VERBALE              32922
#define ID_SBLOCCACERTIFICAZIONE        32923
#define ID_NOTACREDITO_NUOVA            32924
#define ID_BUTTON_AGGIORNA_AZIENDE      32928
#define ID_STAMPA_ETICHETTE             32929
#define ID_BUTTON_AGGIORNAMATERIALI     32931
#define ID_BUTTON_AGGIORNAOPERATORI     32932
#define ID_BUTTON_AGGIORNAPAGAMENTI     32933
#define ID_BUTTON_AGGIORNAMARCHI        32934
#define ID_BUTTON_AGGIORNA              32935
#define ID_SBLOCCA_FATTURA              32937
#define ID_SBLOCCAFATTURA               32938
#define ID_SBLOCCAFATTURAZIONE          32939
#define ID_FIND_VERB_STRUTTURA          32940
#define ID_REPORT_VERBALI               32941
#define ID_PRINT_SCHEDA_INT_FATTURA     32942
#define ID_DEL_INFATTURAZIONE           32943
#define ID_FIND_VERB_SIGLA              32945
#define ID_INSERTVERBALE                32946
#define ID_PRN_FATTURA_PROFORMA         32947
#define IDD_PREVIEW_DOC                 32948
#define IDD_OPEN_DOC                    32949
#define ID_LISTINI_STAMPA_INCONCESSIONE 32953
#define ID_FATTURA_ARCHIVIA_SINGOLAFATTURA 32954
#define ID_FATTURA_ARCHIVIA_GRUPPOFATTURE 32955
#define ID_NUOVO_GEOLOGIA               32956
#define ID_HELP_VERSIONEWINSIGMA        32962
#define ID_HELP_HELPMANUAL              32963
#define ID_HELP_HELP                    32964
#define ID_AZIENDE                      32967
#define ID_AZIENDE_NUOVA                32968
#define ID_AZIENDE_MODIFICA             32969
#define ID_AZIENDE_ELIMINA              32970
#define ID_HELP_VERSION                 32974
#define ID_HELP_HELPF1                  33012
#define ID_FIND_VERB_NUMERO             33033
#define ID_BUTTON33034                  33034
#define ID_ESPORTA_FATTURE              33035
#define ID_FATTURA_ESPORTAFATTURE       33036
#define ID_VERBALI_MODIFICA             33040
#define ID_VERBALI_ANNULLA              33041
#define ID_VERBALI_CHIUDI               33042
#define ID_VERBALI_METTIINFATTURAZIONE  33043
#define ID_FATTURA_ELETT_EMETTI         33044
#define ID_STAMPA_CON_HEADER            33045
#define ID_BUTTON_STAMPA_CERTIFICATI    33046
#define ID_ARCHIVIOFATTURE_STAMPA_DOPPIACOPIASENZAHEADER 33048
#define ID_ARCHIVIOFATTURE_STAMPA_SINGOLACOPIASENZAHEADER 33049
#define ID_BUTTON_STAMPA_CERTIFICATI_SENZA_HEADER 33050
#define ID_VERBALI_STAMPA_VERBALECONINTESTAZIONE 33051
#define ID_FATTURA_ESPORTAXML           33052
#define ID_FATTURA_XML                  33053

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        270
#define _APS_NEXT_COMMAND_VALUE         33054
#define _APS_NEXT_CONTROL_VALUE         1590
#define _APS_NEXT_SYMED_VALUE           196
#endif
#endif
