ALTER TABLE `FATTURE`
	CHANGE COLUMN `OrdineAcquisto` `OrdineAcquisto` VARCHAR(200) NULL DEFAULT NULL AFTER `CIG`,
	CHANGE COLUMN `Contratto` `Contratto` VARCHAR(200) NULL DEFAULT NULL AFTER `DataOrdineAcquisto`;
